services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: cattleya
      POSTGRES_PASSWORD: cattleya
      POSTGRES_DB: cattleya
    ports:
      - "5432:5432"
    volumes:
      - cattleya_pg_data:/var/lib/postgresql/data

volumes:
  cattleya_pg_data:
