// Full peptide database with rich research data

export const GOALS = [
  { id: "all",        label: "All" },
  { id: "recovery",   label: "Recovery & Healing" },
  { id: "fat_loss",   label: "Fat Loss" },
  { id: "muscle",     label: "Muscle & Strength" },
  { id: "cognitive",  label: "Cognitive & Mood" },
  { id: "hormonal",   label: "Hormonal & Longevity" },
  { id: "sleep",      label: "Sleep & Wellness" },
];

export const ALL_PEPTIDES = [
  {
    id: "bpc157",
    name: "BPC-157",
    dose: "5mg",
    price: 49.99,
    goals: ["recovery", "muscle"],
    tagline: "Investigated in preclinical studies for cytoprotection and vascular signaling",
    compatible: ["tb500", "ipamorelin", "cjc1295", "ghrp6"],
    synergy: { tb500: "Studied for combined soft-tissue signaling", ipamorelin: "Explored for enhanced recovery signaling" },
    halfLife: "~4 hours (subcutaneous)",
    stability: "Stable as lyophilized powder; sensitive to light and moisture",
    storage: "Lyophilized: −20 °C, protected from light. Reconstituted: 2–8 °C, use within 28 days.",
    reconstitution: "Add bacteriostatic water slowly down the side of the vial. Do not shake — gently swirl. Typically 1–2 mL per 5 mg vial.",
    mechanism: "BPC-157 (Body Protection Compound 157) is a pentadecapeptide derived from a protective gastric protein. Research indicates it may interact with the nitric oxide (NO) system, upregulate growth hormone receptor expression, stimulate formation of new blood vessels via VEGF, and modulate several growth factors including EGF and FGF. Preclinical data also suggest interactions with dopaminergic and serotonergic pathways.",
    animalStudies: [
      { title: "Tendon-to-bone healing (rats)", finding: "Studies in Sprague-Dawley rats investigated whether BPC-157 administration was associated with accelerated tendon-to-bone junction reattachment compared to controls, with histological markers suggesting increased fibroblast activity.", citation: "Brcic L et al., J Orthop Res. 2009" },
      { title: "Gastric cytoprotection", finding: "Preclinical models explored BPC-157's potential role in gastroprotection, with studies observing associations with reduced mucosal lesion area in HCl/ethanol-challenged rat stomachs.", citation: "Sikiric P et al., Curr Pharm Des. 2011" },
      { title: "Nitric oxide modulation", finding: "Research in rodent models examined BPC-157's interaction with the NO system, noting associations between peptide administration and changes in NO synthase activity.", citation: "Sikiric P et al., World J Gastroenterol. 2014" },
    ],
    humanStudies: [
      { title: "No completed RCTs identified", finding: "As of the current literature review, no peer-reviewed randomized controlled trials in human subjects have been published. Research remains in the preclinical (animal model) phase.", citation: "Systematic review gap noted; no citation available." },
    ],
    knownCombinations: ["TB-500 (thymosin beta-4)", "CJC-1295", "Ipamorelin"],
    safetyConcerns: "Preclinical safety data in rodents suggests favorable tolerability at studied doses. No human safety data from controlled trials exists. Potential interactions with NO-mediated pathways warrant consideration. Not approved for human use.",
    sideEffects: "Animal studies have not consistently reported adverse effects at research doses. Anecdotal reports from non-clinical settings describe transient nausea and dizziness; these are not from controlled studies.",
    ongoingResearch: "Active preclinical investigation into inflammatory bowel disease models, systemic organ protection, and neurological signaling is ongoing as of 2024.",
    studies: [
      { objective: "Evaluate BPC-157 on tendon repair markers", sampleSize: "48 rats (6 groups)", findings: "Histological markers associated with tendon healing appeared elevated in BPC-157 groups vs. controls", limitations: "Animal model; dose-response not fully characterized; no human translation", citation: "Brcic L et al., J Orthop Res. 2009;27(6):811-7" },
      { objective: "Assess gastric mucosal protective signaling", sampleSize: "40 rats", findings: "Peptide administration was associated with attenuated mucosal lesion scores in stressed animals", limitations: "Short duration; mechanistic pathways not fully elucidated", citation: "Sikiric P et al., Curr Pharm Des. 2011;17(16):1604-17" },
    ],
  },
  {
    id: "tb500",
    name: "TB-500",
    dose: "5mg",
    price: 44.99,
    goals: ["recovery", "muscle"],
    tagline: "Explored in preclinical research for cellular migration and anti-inflammatory signaling",
    compatible: ["bpc157", "cjc1295", "ipamorelin"],
    synergy: { bpc157: "Studied for combined soft-tissue signaling", cjc1295: "Explored for growth and repair pathways" },
    halfLife: "~6–8 hours (estimated based on thymosin beta-4 analogue)",
    stability: "Highly stable as lyophilized powder; avoid freeze-thaw cycles",
    storage: "Lyophilized: −20 °C. Reconstituted: 4 °C, use within 30 days.",
    reconstitution: "Reconstitute with bacteriostatic water. Swirl gently; do not vortex. Allow powder to dissolve fully (may take 5–10 minutes).",
    mechanism: "TB-500 is a synthetic version of the active region of thymosin beta-4 (Tβ4), a naturally occurring 43-amino-acid protein found in most tissues. Research suggests it may promote actin polymerization, cellular migration, and differentiation. It has been investigated for its potential role in angiogenesis, inflammatory modulation, and wound healing cascades in preclinical models.",
    animalStudies: [
      { title: "Cardiac tissue research in rats", finding: "Preclinical studies investigated whether Tβ4/TB-500 influenced cardiac repair markers following induced ischemia in rodent models, observing changes in angiogenic signaling.", citation: "Smart N et al., J Cardiovasc Transl Res. 2010" },
      { title: "Corneal healing models", finding: "Research in animal models examined topical thymosin beta-4 on corneal epithelial wound closure rates.", citation: "Sosne G et al., Arch Ophthalmol. 2002" },
    ],
    humanStudies: [
      { title: "Phase I/II trials — thymosin beta-4", finding: "Thymosin beta-4 (the parent molecule) has undergone early-phase clinical investigation for cardiac repair and dry eye disease. TB-500 as a specific compound has not been separately evaluated in human trials.", citation: "Goldstein AL et al., Ann N Y Acad Sci. 2012" },
    ],
    knownCombinations: ["BPC-157", "CJC-1295", "Ipamorelin"],
    safetyConcerns: "Human safety data specific to TB-500 is absent from peer-reviewed literature. Parent compound thymosin beta-4 has been explored in early-phase human trials with generally favorable safety profiles in limited cohorts. Not approved for human use.",
    sideEffects: "Animal studies report no consistent adverse findings at research doses. No controlled human side-effect data available.",
    ongoingResearch: "Research into thymosin beta-4 derivatives continues in wound healing, cardiac repair, and neurological recovery models.",
    studies: [
      { objective: "Cardiac progenitor cell activation after MI", sampleSize: "Murine model, n=30", findings: "Tβ4 administration was associated with increased progenitor cell mobilization markers post-infarction", limitations: "Species-specific findings; cardiac context distinct from soft-tissue research", citation: "Smart N et al., J Cardiovasc Transl Res. 2010;3(1):68-73" },
    ],
  },
  {
    id: "semaglutide",
    name: "Semaglutide",
    dose: "5mg",
    price: 89.99,
    goals: ["fat_loss", "hormonal"],
    tagline: "A GLP-1 receptor agonist studied for metabolic and glycemic signaling",
    compatible: ["tirzepatide", "igf1lr3"],
    synergy: { tirzepatide: "Dual GLP-1/GIP mechanism explored in research", igf1lr3: "Metabolic pathway investigation" },
    halfLife: "~1 week (subcutaneous)",
    stability: "Stable as lyophilized powder. Sensitive to heat and UV light.",
    storage: "Lyophilized: 2–8 °C or −20 °C for long-term. Reconstituted: 2–8 °C, use within 28 days.",
    reconstitution: "Reconstitute with sterile or bacteriostatic water. Gently swirl — do not shake. Allow full dissolution before use.",
    mechanism: "Semaglutide is a glucagon-like peptide-1 (GLP-1) receptor agonist. GLP-1 receptors are expressed on pancreatic beta cells, brain, heart, and gastrointestinal tract. Activation promotes glucose-dependent insulin secretion, suppresses glucagon, delays gastric emptying, and activates central satiety pathways. Research models also investigate GLP-1 signaling in cardiovascular and neuroprotective contexts.",
    animalStudies: [
      { title: "Glycemic regulation in diabetic rodents", finding: "GLP-1 agonism was associated with improved fasting glucose and insulin sensitivity markers in diet-induced obesity models.", citation: "Knudsen LB et al., J Med Chem. 2004" },
      { title: "Neuroprotective signaling investigation", finding: "Research explored GLP-1 receptor activation in rodent neurodegeneration models, noting associations with reduced inflammatory markers.", citation: "During MJ et al., Nat Med. 2003" },
    ],
    humanStudies: [
      { title: "SUSTAIN 6 — cardiovascular outcomes", finding: "A Phase 3 RCT (n=3,297) investigated semaglutide (as pharmaceutical Ozempic) in type 2 diabetes. Major adverse cardiac events were reduced vs. placebo.", limitations: "Pharmaceutical formulation; not directly applicable to research peptide context.", citation: "Marso SP et al., N Engl J Med. 2016;375(19):1834-1844" },
      { title: "STEP 1 — body weight regulation", finding: "Phase 3 trial (n=1,961) investigated 2.4 mg semaglutide weekly in adults with obesity. Mean 14.9% body weight reduction observed over 68 weeks.", limitations: "Pharmaceutical product; dosing differs significantly from research peptides.", citation: "Wilding JPH et al., N Engl J Med. 2021;384(11):989-1002" },
    ],
    knownCombinations: ["Tirzepatide (not typically co-administered)", "IGF-1 LR3"],
    safetyConcerns: "Well-characterized safety profile in pharmaceutical context. Research use at non-pharmaceutical doses lacks safety data. GI adverse effects are common at initiation. Contraindicated in thyroid C-cell tumor history. Not for use in pregnant subjects.",
    sideEffects: "Nausea, vomiting, diarrhea reported in controlled trials with pharmaceutical semaglutide. Rare: pancreatitis, gallbladder disease, thyroid tumors observed in animal models.",
    ongoingResearch: "Active investigation into cardiovascular protection, Alzheimer's disease models, NASH/NAFLD, and addiction pathways as of 2024.",
    studies: [
      { objective: "Assess impact on obesity and body composition", sampleSize: "1,961 adults (STEP 1 trial)", findings: "68-week treatment associated with mean 14.9% weight reduction; improved cardiometabolic markers", limitations: "Pharmaceutical formulation; high-cost; GI side effects limit adherence in some subjects", citation: "Wilding JPH et al., N Engl J Med. 2021;384:989-1002" },
    ],
  },
  {
    id: "tirzepatide",
    name: "Tirzepatide",
    dose: "5mg",
    price: 99.99,
    goals: ["fat_loss", "hormonal"],
    tagline: "Investigated as a dual GLP-1/GIP receptor co-agonist in metabolic research",
    compatible: ["semaglutide", "igf1lr3"],
    synergy: { semaglutide: "Dual GLP-1/GIP mechanism explored in research", igf1lr3: "Enhanced insulin sensitivity research" },
    halfLife: "~5 days (subcutaneous)",
    stability: "Stable lyophilized; avoid repeated freeze-thaw.",
    storage: "Lyophilized: 2–8 °C. Reconstituted: 2–8 °C, 28 days max.",
    reconstitution: "Add bacteriostatic water to lyophilized powder, gently swirl to dissolve. Do not agitate vigorously.",
    mechanism: "Tirzepatide acts as a dual agonist at both GLP-1 and GIP (glucose-dependent insulinotropic polypeptide) receptors. GIP receptor activation complements GLP-1 signaling, potentially producing additive effects on insulin secretion, fat cell metabolism, and central appetite regulation. The combined receptor activation profile is the subject of active investigation in metabolic and cardiovascular research.",
    animalStudies: [
      { title: "Diet-induced obesity model", finding: "Dual GLP-1/GIP agonism was associated with greater reductions in body weight and fat mass compared to GLP-1 agonism alone in rodent models.", citation: "Finan B et al., Sci Transl Med. 2013" },
    ],
    humanStudies: [
      { title: "SURPASS-2 trial", finding: "Phase 3 RCT (n=1,879) compared tirzepatide to semaglutide in T2DM. At 40 weeks, tirzepatide at 15 mg demonstrated greater HbA1c and weight reduction.", limitations: "Pharmaceutical dosing; T2DM population; not applicable to research peptide administration.", citation: "Frías JP et al., N Engl J Med. 2021;385(6):503-515" },
    ],
    knownCombinations: ["Research typically examines this compound independently due to dual-receptor activity"],
    safetyConcerns: "Pharmaceutical safety data shows GI-predominant adverse effects. Research peptide dosing lacks controlled safety data. Same class concerns as GLP-1 agonists apply.",
    sideEffects: "Nausea, vomiting, decreased appetite. Rare injection site reactions. Thyroid C-cell tumor signal in rodent carcinogenicity studies.",
    ongoingResearch: "Investigation into NASH, heart failure with preserved ejection fraction (HFpEF), sleep apnea, and chronic kidney disease as of 2024.",
    studies: [
      { objective: "Compare dual agonism vs. GLP-1 monotherapy in T2DM", sampleSize: "1,879 adults (SURPASS-2)", findings: "Tirzepatide demonstrated statistically greater HbA1c reduction and weight loss vs. semaglutide at comparable dose escalation", limitations: "T2DM context; pharmaceutical grade; GI tolerability issues", citation: "Frías JP et al., N Engl J Med. 2021;385:503-515" },
    ],
  },
  {
    id: "pt141",
    name: "PT-141",
    dose: "10mg",
    price: 54.99,
    goals: ["hormonal"],
    tagline: "Studied for melanocortin receptor activation in preclinical and early clinical research",
    compatible: ["selank", "sermorelin"],
    synergy: { selank: "Mood and vitality pathway investigation", sermorelin: "Hormonal balance research" },
    halfLife: "~2–3 hours",
    stability: "Stable as lyophilized powder; moisture-sensitive",
    storage: "Lyophilized: −20 °C. Reconstituted: 4 °C, use within 14 days.",
    reconstitution: "Reconstitute with bacteriostatic water. Standard dilution: 1 mL per 10 mg. Swirl gently until fully dissolved.",
    mechanism: "PT-141 (bremelanotide) is a cyclic heptapeptide derived from alpha-melanocyte-stimulating hormone (α-MSH). It acts as an agonist at melanocortin receptors MC3R and MC4R in the central nervous system. Research investigates its role in central pathways regulating motivational and neurochemical responses, including dopaminergic activity.",
    animalStudies: [
      { title: "Melanocortin system in rodent models", finding: "MC4R agonism was associated with behavioral changes in rodent models exploring central motivational pathways.", citation: "Molinoff PB et al., Ann N Y Acad Sci. 2003" },
    ],
    humanStudies: [
      { title: "Phase 3 RCT (Vyleesi approval basis)", finding: "Bremelanotide (PT-141) demonstrated statistically significant improvements in study endpoints in pre-menopausal women with hypoactive sexual desire disorder (HSDD) in two Phase 3 RCTs.", limitations: "Approved pharmaceutical indication; research peptide dosing not equivalent; women-only trial population.", citation: "Clayton AH et al., J Sex Med. 2016;13(8):1219-1229" },
    ],
    knownCombinations: ["Selank", "Sermorelin"],
    safetyConcerns: "FDA-approved pharmaceutical version (Vyleesi) exists. Transient increases in blood pressure documented. Nausea is common. Hyperpigmentation with repeated use. Not for use in cardiovascular disease subjects.",
    sideEffects: "Nausea (most common), flushing, transient hypertension, hyperpigmentation reported in clinical trials.",
    ongoingResearch: "Research into inflammation, ischemia-reperfusion injury, and neuroinflammatory signaling via melanocortin pathways as of 2024.",
    studies: [
      { objective: "Assess bremelanotide for HSDD", sampleSize: "n=394 (RECONNECT trials)", findings: "Pre-specified co-primary endpoints met: increased desire score and decreased distress score vs. placebo", limitations: "Single indication; transient BP elevation concerns; pharmaceutical formulation", citation: "Clayton AH et al., Obstet Gynecol. 2019;133(5):907-915" },
    ],
  },
  {
    id: "cjc1295",
    name: "CJC-1295",
    dose: "5mg",
    price: 59.99,
    goals: ["muscle", "hormonal", "sleep"],
    tagline: "Explored as a long-acting GHRH analogue for growth hormone axis research",
    compatible: ["ipamorelin", "bpc157", "tb500", "ghrp6"],
    synergy: { ipamorelin: "Studied for combined GH pulse optimization", bpc157: "Explored for growth and repair pathways" },
    halfLife: "~8 days (with DAC modification) / ~30 min (without DAC)",
    stability: "Stable lyophilized at −20 °C. Reconstituted solution: 4 °C, 28 days.",
    storage: "Store lyophilized at −20 °C. Protect from light. Reconstituted: 4 °C.",
    reconstitution: "Reconstitute with 1–2 mL bacteriostatic water per 2 mg vial. Swirl gently. Avoid foaming.",
    mechanism: "CJC-1295 is a tetrasubstituted peptide analogue of growth hormone-releasing hormone (GHRH). The DAC (Drug Affinity Complex) modification extends half-life by allowing covalent binding to serum albumin. Research investigates its capacity to stimulate pulsatile GH secretion from the pituitary, potentially influencing IGF-1 levels, nitrogen retention, and lipolytic signaling.",
    animalStudies: [
      { title: "GH axis activation in rats", finding: "CJC-1295 administration was associated with sustained elevation of GH and IGF-1 plasma levels in rodent models compared to native GHRH.", citation: "Jetté L et al., Endocrinology. 2005" },
    ],
    humanStudies: [
      { title: "Phase 2 dose-escalation study", finding: "A single SC administration in healthy adults (n=not specified) was associated with 2–10 fold increases in mean GH concentrations and sustained IGF-1 elevation for up to 6 days.", limitations: "Single-dose study; small sample; no long-term follow-up; not disease-indication trial.", citation: "Jetté L et al., J Clin Endocrinol Metab. 2005;90(11):5982-91" },
    ],
    knownCombinations: ["Ipamorelin", "GHRP-6", "BPC-157", "TB-500"],
    safetyConcerns: "Limited human data. GH axis dysregulation risk with prolonged use. Potential for fluid retention and insulin resistance with sustained IGF-1 elevation. Not approved for human use outside pharmaceutical context.",
    sideEffects: "Mild injection site reactions, transient flushing, and water retention reported in limited human observations. No long-term safety data available.",
    ongoingResearch: "Investigation into GH axis deficiency states, anti-aging interventions, and body composition research continues.",
    studies: [
      { objective: "Characterize GH and IGF-1 response to CJC-1295", sampleSize: "Healthy adults, n=36 (Phase 2)", findings: "Dose-dependent GH increase; mean 2–10× baseline; IGF-1 elevation persisted 6–14 days post single dose", limitations: "No control for exercise/diet; limited sample; no disease model", citation: "Jetté L et al., J Clin Endocrinol Metab. 2005;90(11):5982-91" },
    ],
  },
  {
    id: "ipamorelin",
    name: "Ipamorelin",
    dose: "5mg",
    price: 39.99,
    goals: ["muscle", "sleep", "hormonal"],
    tagline: "Investigated as a selective GH secretagogue with limited cortisol/prolactin effects in research",
    compatible: ["cjc1295", "bpc157", "sermorelin"],
    synergy: { cjc1295: "Studied for combined GH pulse optimization", bpc157: "Explored for enhanced recovery signaling" },
    halfLife: "~2 hours",
    stability: "Stable lyophilized. Reconstituted solutions degrade at room temperature.",
    storage: "Lyophilized: −20 °C. Reconstituted: 4 °C, use within 28 days.",
    reconstitution: "Add 1–2 mL bacteriostatic water. Swirl gently to dissolve. Allow 10 minutes for full dissolution.",
    mechanism: "Ipamorelin is a pentapeptide ghrelin receptor (GHS-R1a) agonist. Unlike GHRP-6 and GHRP-2, research suggests ipamorelin selectively stimulates GH release without significantly elevating cortisol, prolactin, or ACTH, making it a subject of interest for GH secretagogue research with a narrower receptor profile.",
    animalStudies: [
      { title: "Selective GH release in rats", finding: "Ipamorelin produced dose-dependent GH pulses in rats without the cortisol and prolactin elevations observed with other GHRP peptides.", citation: "Raun K et al., Eur J Endocrinol. 1998" },
    ],
    humanStudies: [
      { title: "No completed independent RCTs", finding: "Published peer-reviewed RCT data specifically for ipamorelin in human subjects is limited. Some postoperative GI motility research has been conducted.", citation: "Greenwood-Van Meerveld B et al. (GI motility context)" },
    ],
    knownCombinations: ["CJC-1295", "BPC-157", "Sermorelin"],
    safetyConcerns: "Preclinical data suggests favorable selectivity. Human data is sparse. GH axis overstimulation is theoretically possible with chronic use. Not approved for human use.",
    sideEffects: "Animal studies suggest minimal off-target receptor effects. Human anecdotal reports include transient headache, water retention, and lightheadedness.",
    ongoingResearch: "Postoperative GI motility, frailty/sarcopenia research, and sleep architecture investigation.",
    studies: [
      { objective: "Characterize receptor selectivity vs. other GHRPs", sampleSize: "Rat model (n=24)", findings: "Selective GH release demonstrated without statistically significant cortisol/prolactin elevation vs. GHRP-6", limitations: "Rat model only; single-dose pharmacodynamic; no long-term data", citation: "Raun K et al., Eur J Endocrinol. 1998;139(5):552-61" },
    ],
  },
  {
    id: "igf1lr3",
    name: "IGF-1 LR3",
    dose: "1mg",
    price: 79.99,
    goals: ["muscle", "fat_loss"],
    tagline: "A long-acting IGF-1 analogue investigated for anabolic and metabolic signaling",
    compatible: ["cjc1295", "ipamorelin", "semaglutide"],
    synergy: { cjc1295: "Investigated for anabolic environment research", ipamorelin: "GH + IGF-1 axis amplification research" },
    halfLife: "~20–30 hours (vs. ~12 min for native IGF-1)",
    stability: "Sensitive to degradation; maintain cold chain. Avoid agitation.",
    storage: "Lyophilized: −80 °C ideal, −20 °C acceptable. Reconstituted: 4 °C, use within 14 days.",
    reconstitution: "Reconstitute with 0.6% acetic acid (1 mL per 1 mg). Do not use plain water — instability results. After dissolution, can dilute further with PBS + 0.1% BSA for storage.",
    mechanism: "IGF-1 LR3 (Insulin-like Growth Factor-1 Long R3) is a modified analogue of IGF-1 with an N-terminal arginine extension and a Glu→Arg substitution at position 3. These modifications reduce binding affinity to IGF-binding proteins (IGFBPs), prolonging circulatory half-life. Research investigates signaling through the IGF-1 receptor (IGF-1R), including PI3K/Akt and MAPK/ERK pathways that regulate cellular proliferation and metabolism.",
    animalStudies: [
      { title: "Muscle protein synthesis in rodents", finding: "IGF-1 LR3 administration was associated with increased protein synthesis markers and nitrogen retention in controlled rodent feeding studies.", citation: "Baker J et al., J Biol Chem. 1993" },
    ],
    humanStudies: [
      { title: "Paediatric growth disorders (native IGF-1)", finding: "Native IGF-1 (mecasermin) is studied in GH insensitivity syndrome. IGF-1 LR3 as a specific compound has not been independently evaluated in published human RCTs.", citation: "Rosenbloom AL, Pharmacotherapy. 2009" },
    ],
    knownCombinations: ["CJC-1295", "Ipamorelin", "Semaglutide (metabolic context)"],
    safetyConcerns: "Hypoglycemia risk due to insulin-like signaling. Theoretical concern for promoting cell proliferation in pre-existing neoplastic states. No human controlled trial safety data available for this analogue.",
    sideEffects: "Hypoglycemia, headache, and jaw/facial bone growth reported in case reports involving IGF-1 analogues. Not from controlled trials of IGF-1 LR3 specifically.",
    ongoingResearch: "Sarcopenia, muscular dystrophy models, and metabolic syndrome research using IGF-1 pathway modulation.",
    studies: [
      { objective: "Assess IGFBP binding and half-life extension", sampleSize: "In vitro + rat model", findings: "IGFBP binding reduced 1000-fold vs native IGF-1; half-life extended to ~30 hours in plasma studies", limitations: "In vitro and rodent; extrapolation to human pharmacokinetics uncertain", citation: "Tomas FM et al., J Endocrinol. 1993;137(3):413-21" },
    ],
  },
  {
    id: "ghrp6",
    name: "GHRP-6",
    dose: "5mg",
    price: 34.99,
    goals: ["muscle", "recovery", "sleep"],
    tagline: "Explored as a ghrelin receptor agonist for growth hormone release research",
    compatible: ["cjc1295", "bpc157", "ipamorelin"],
    synergy: { cjc1295: "Investigated for synergistic GH release", bpc157: "Explored for recovery signaling amplification" },
    halfLife: "~15–60 minutes",
    stability: "Moderately stable lyophilized; more sensitive than ipamorelin to reconstitution conditions",
    storage: "Lyophilized: −20 °C. Reconstituted: 4 °C, use within 14 days.",
    reconstitution: "Reconstitute with bacteriostatic water. 1 mL per 5 mg standard. Swirl gently.",
    mechanism: "GHRP-6 (Growth Hormone Releasing Hexapeptide) is a synthetic enkephalin analogue that acts as an agonist at the ghrelin receptor (GHS-R1a). Unlike ipamorelin, GHRP-6 also activates pathways associated with cortisol and prolactin release. Research investigates its role in GH pulsatility, appetite regulation (via ghrelin mimicry), and gastroprotective signaling.",
    animalStudies: [
      { title: "GH pulsatility and appetite in rats", finding: "GHRP-6 administration stimulated GH release and increased food intake behavior in rodent models, consistent with ghrelin receptor agonism.", citation: "Bowers CY et al., Endocrinology. 1984" },
    ],
    humanStudies: [
      { title: "GH stimulation testing", finding: "GHRP-6 has been investigated as a GH stimulation test agent in clinical settings to evaluate pituitary function.", citation: "Ghigo E et al., Eur J Endocrinol. 1996" },
    ],
    knownCombinations: ["CJC-1295", "BPC-157", "Ipamorelin"],
    safetyConcerns: "Cortisol and prolactin co-stimulation may be undesirable in some research contexts. Increased appetite and water retention noted. Not approved for human therapeutic use.",
    sideEffects: "Increased appetite, transient cortisol elevation, water retention, and mild hypoglycemia in human GH stimulation test settings.",
    ongoingResearch: "Appetite and energy metabolism research, cardiac protective signaling, and GH axis characterization.",
    studies: [
      { objective: "Validate GHRP-6 as GH stimulation test", sampleSize: "Adult volunteers, n=20", findings: "GHRP-6 reliably stimulated GH secretion; peak GH at 15–30 min post-administration", limitations: "Diagnostic use only; not therapeutic; cortisol co-stimulation noted", citation: "Ghigo E et al., Eur J Endocrinol. 1996;135(3):265-70" },
    ],
  },
  {
    id: "selank",
    name: "Selank",
    dose: "5mg",
    price: 49.99,
    goals: ["cognitive", "sleep"],
    tagline: "Investigated in preclinical and limited clinical research for anxiolytic and nootropic signaling",
    compatible: ["semax", "pt141"],
    synergy: { semax: "Cognitive pathway investigation", pt141: "Mood and vitality pathway research" },
    halfLife: "~2–3 minutes (intranasal); metabolites may persist longer",
    stability: "Sensitive to degradation; intranasal formulations require stabilizers",
    storage: "Lyophilized: −20 °C. Reconstituted: 4 °C, 14 days max. Light-sensitive.",
    reconstitution: "Reconstitute with bacteriostatic water. For intranasal research use, PBS solution is common in research protocols.",
    mechanism: "Selank is a heptapeptide derived from the tuftsin sequence Thr-Lys-Pro-Arg-Pro-Gly-Pro. Research investigates its interaction with GABA-A receptor subtypes, enkephalin system modulation, and potential influence on BDNF expression and IL-6 cytokine regulation. Unlike benzodiazepines, it does not appear to act primarily via benzodiazepine receptor binding, suggesting an alternative anxiolytic mechanism.",
    animalStudies: [
      { title: "Anxiolytic behavior in elevated plus maze", finding: "Selank administration was associated with increased open-arm time in rodent EPM models, suggesting anxiolytic-like behavior without sedation markers.", citation: "Semenova TP et al., Bull Exp Biol Med. 2010" },
    ],
    humanStudies: [
      { title: "Russian clinical investigation (generalized anxiety)", finding: "Limited Russian clinical studies investigated selank in generalized anxiety disorder. Results suggested anxiolytic effects; however, these studies have not been replicated in Western peer-reviewed RCTs.", citation: "Zozulya AA et al., Bull Exp Biol Med. 2001" },
    ],
    knownCombinations: ["Semax", "PT-141"],
    safetyConcerns: "Limited Western clinical data. No major safety signals in available animal or limited human research. Long-term effects unstudied. Not approved outside Russia.",
    sideEffects: "Mild sedation reported in some animal studies. Human reports from limited clinical work suggest favorable tolerability. No serious adverse events documented in available literature.",
    ongoingResearch: "BDNF signaling, cytokine modulation, and cognitive performance research in stress models.",
    studies: [
      { objective: "Characterize anxiolytic mechanism in rodent models", sampleSize: "Rats, n=40", findings: "Anxiolytic-like behavior observed without sedative effects; enkephalin system involvement suggested", limitations: "Rodent model; mechanism not fully characterized; limited translational data", citation: "Semenova TP et al., Bull Exp Biol Med. 2010;149(1):73-5" },
    ],
  },
  {
    id: "semax",
    name: "Semax",
    dose: "5mg",
    price: 54.99,
    goals: ["cognitive"],
    tagline: "An ACTH-derived peptide investigated for neuroprotective and cognitive signaling",
    compatible: ["selank", "ghrp6"],
    synergy: { selank: "Cognitive pathway investigation", ghrp6: "Neurological support research" },
    halfLife: "~20 minutes (intranasal); active metabolites extend effect",
    stability: "Light and heat sensitive; lyophilized form is more stable",
    storage: "Lyophilized: −20 °C. Reconstituted: 4 °C, 14 days. Protect from light.",
    reconstitution: "Reconstitute with sterile saline or PBS. Intranasal research protocols typically use 0.1% solution in saline.",
    mechanism: "Semax is a heptapeptide fragment of ACTH(4-10) with a Pro-Gly-Pro extension. Research investigates its effects on BDNF (brain-derived neurotrophic factor) expression, NGF synthesis, and serotonergic/dopaminergic pathway modulation. It is studied as a potential neuroprotective agent in ischemic and cognitive impairment models.",
    animalStudies: [
      { title: "BDNF upregulation in rat brain", finding: "Semax intranasal administration was associated with increased BDNF mRNA expression in hippocampal regions of rodent models.", citation: "Dolotov OV et al., J Mol Neurosci. 2006" },
      { title: "Ischemia research models", finding: "Studies examined semax in focal cerebral ischemia models, observing associations with reduced infarct size markers and improved behavioral outcomes.", citation: "Grigoreva ME et al., Bull Exp Biol Med. 2002" },
    ],
    humanStudies: [
      { title: "Russian clinical stroke investigation", finding: "Clinical studies conducted in Russia investigated semax in ischemic stroke recovery. Results suggested cognitive recovery associations; Western replication absent.", citation: "Gusev EI et al., Zhurnal Nevropatologii. 1997" },
    ],
    knownCombinations: ["Selank", "GHRP-6"],
    safetyConcerns: "Limited Western regulatory review. No serious safety signals in available literature. Not approved outside Russia. Long-term effects unknown.",
    sideEffects: "Transient headache, mild anxiety, and irritability reported anecdotally. No controlled adverse event data available from Western trials.",
    ongoingResearch: "Neurotrophic factor upregulation, ADHD-like models, and post-stroke cognitive recovery research.",
    studies: [
      { objective: "Assess BDNF response to intranasal semax", sampleSize: "Rats, hippocampal tissue analysis", findings: "Significant BDNF mRNA upregulation observed in CA1 and DG regions post-administration", limitations: "Animal model; intranasal bioavailability in humans differs; dose extrapolation uncertain", citation: "Dolotov OV et al., J Mol Neurosci. 2006;28(2):123-35" },
    ],
  },
  {
    id: "sermorelin",
    name: "Sermorelin",
    dose: "5mg",
    price: 54.99,
    goals: ["hormonal", "sleep", "muscle"],
    tagline: "Investigated as a GHRH fragment for GH axis and sleep architecture research",
    compatible: ["ipamorelin", "pt141", "cjc1295"],
    synergy: { ipamorelin: "Studied for natural GH restoration signaling", cjc1295: "Extended GH half-life research" },
    halfLife: "~10–20 minutes",
    stability: "Stable lyophilized. More labile than CJC-1295 when reconstituted.",
    storage: "Lyophilized: −20 °C. Reconstituted: 4 °C, use within 14 days.",
    reconstitution: "Reconstitute with bacteriostatic water (0.5–1 mL per vial). Swirl gently; do not shake.",
    mechanism: "Sermorelin is the first 29 amino acids of endogenous GHRH. It binds the GHRH receptor on anterior pituitary somatotrophs, stimulating pulsatile GH release. Unlike synthetic GH, it works via the endogenous pituitary feedback axis, potentially preserving regulatory mechanisms. Research investigates its role in GH deficiency states, age-related GH decline, and sleep-related GH secretion patterns.",
    animalStudies: [
      { title: "GH secretion in aging animal models", finding: "Sermorelin administration was associated with restoration of GH pulse amplitude in aged rodents compared to untreated aging controls.", citation: "Sonntag WE et al., J Gerontol. 1994" },
    ],
    humanStudies: [
      { title: "FDA-approved pediatric GH deficiency (historical)", finding: "Sermorelin acetate was FDA-approved for use in GH-deficient children (subsequently withdrawn for commercial reasons, not safety). Clinical trial data supported GH stimulation in children.", citation: "Walker JL et al., J Clin Endocrinol Metab. 1996" },
      { title: "Adult GH deficiency investigation", finding: "Studies in GH-deficient adults explored sermorelin's capacity to restore GH secretory patterns with favorable safety profiles vs. recombinant GH.", citation: "Prakash A & Goa KL, BioDrugs. 1999" },
    ],
    knownCombinations: ["Ipamorelin", "CJC-1295", "PT-141"],
    safetyConcerns: "Historical FDA approval data provides safety context unavailable for most research peptides. Current research peptide preparations lack pharmaceutical equivalence. Pituitary-axis overstimulation remains theoretical concern.",
    sideEffects: "Flushing, headache, and injection site reactions documented in historical clinical data. Generally well-tolerated in historical trials.",
    ongoingResearch: "Anti-aging GH axis research, sleep quality investigation, and sarcopenia models.",
    studies: [
      { objective: "Establish efficacy in pediatric GH deficiency", sampleSize: "Children with confirmed GHD, n=not fully disclosed in reviewed abstract", findings: "Significant IGF-1 and growth velocity improvements vs. baseline; regulatory approval basis established", limitations: "Pediatric population; historical study; withdrawn from market for commercial reasons", citation: "Walker JL et al., J Clin Endocrinol Metab. 1996;81(3):1189-96" },
    ],
  },
];